name: Verovio CI (build JS toolkit)

on:
  # Trigger the workflow when specified workflow is completed
  workflow_run:
    workflows: ['Verovio CI (build C++)']
    types:
      - completed
    # build C++ workflow runs on push to develop, ci-test or travis-test branch
    branches: [develop, ci-test, travis-test]

# globals
env:
  # emscripten
  EMSCRIPTEN_VERSION: latest
  EMSCRIPTEN_CACHE_FOLDER: emsdk-cache

  # gh-pages
  GH_PAGES_BRANCH: gh-pages
  GH_PAGES_FOLDER: gh-pages

  # build artifacts
  CLI_BUILD: cli-build
  TOOLKIT_BUILD: toolkit-build

  # temp
  TEMP_FOLDER: temp


jobs:
  # Build the CLI artifacts
  build_cli:
    name: Build cli
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Create temp dir
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p $TEMP_FOLDER/

      - name: Run make
        run: |
          cd $GITHUB_WORKSPACE/tools
          cmake ../cmake
          make -j 8

      - name: Update cli.txt
        run: |
          cd $GITHUB_WORKSPACE/tools
          ./verovio -h > $GITHUB_WORKSPACE/$TEMP_FOLDER/cli.txt

      - name: Upload cli artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CLI_BUILD }}
          path: ${{ github.workspace }}/${{ env.TEMP_FOLDER }}/cli.txt

      - name: Check files
        if: always()
        run: |
          cd $GITHUB_WORKSPACE/$TEMP_FOLDER/
          pwd
          ls -al

  # Build the JS toolkit artifacts
  build_js:
    name: Build JS toolkit
    runs-on: ubuntu-latest

    # set matrix with toolkit options (runs the following steps for every target in parallel)
    strategy:
      matrix:
        toolkit:
          - target: nohumdrum
            message: "Building toolkit without humdrum"
            options: "-c -H -M"
            filepath: "verovio-toolkit.js*"
          - target: light
            message: "Building toolkit without humdrum as light version"
            options: "-c -H -l -M"
            filepath: "verovio-toolkit-light.js*"
          - target: wasm
            message: "Building toolkit without humdrum as wasm"
            options: "-c -H -w -M"
            filepath: "verovio*wasm*"
          - target: default
            message: "Building default toolkit (with humdrum)"
            options: "-c -M"
            filepath: "*-hum.js*"

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Cache emsdk artifacts
        id: cache-emsdk
        uses: actions/cache@v2
        with:
          # path for cache
          path: ${{ env.EMSCRIPTEN_CACHE_FOLDER }}
          # key for cache
          key: ${{ runner.os }}-emsdk-${{ env.EMSCRIPTEN_VERSION }}-${{ github.sha }}

      - name: Setup emsdk (use cache if found, create otherwise)
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: ${{ env.EMSCRIPTEN_CACHE_FOLDER }}

      - name: Verify emscripten build
        run: emcc -v

      - name: Create temp dir
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p $TEMP_FOLDER//

      - name: Build Toolkit (${{ matrix.toolkit.target }}) with options ${{ matrix.toolkit.options }}
        run: |
          cd $GITHUB_WORKSPACE/emscripten
          echo "${{ matrix.toolkit.message }}"
          ./buildToolkit ${{ matrix.toolkit.options }}
          cp build/${{ matrix.toolkit.filepath }} $GITHUB_WORKSPACE/$TEMP_FOLDER/

      - name: Upload js build artifact (${{ matrix.toolkit.target }})
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TOOLKIT_BUILD }}
          path: ${{ github.workspace }}/${{ env.TEMP_FOLDER }}/${{ matrix.toolkit.filepath }}

      - name: Check files
        if: always()
        run: |
          cd $GITHUB_WORKSPACE/$TEMP_FOLDER/
          pwd
          ls -al

  # Deploy the build artifacts to gh-pages
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # run deployment only after finishing the build jobs
    needs: [build_cli, build_js]

    steps:
      - name: Checkout GH_PAGES_BRANCH into GH_PAGES_FOLDER
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GH_PAGES_BRANCH }}
          path: ${{ env.GH_PAGES_FOLDER }}

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          #if no name specified, all artifacts are downloaded (here: [cli-build, toolkit-build])
          path: artifacts

      - name: Copy artifacts to gh-pages
        run: |
          cp artifacts/$CLI_BUILD/cli.txt $GH_PAGES_FOLDER/_includes/
          cp artifacts/$TOOLKIT_BUILD/* $GH_PAGES_FOLDER/javascript/develop/

      - name: Check git status
        run: |
          echo ${{ github.repository }}
          cd $GH_PAGES_FOLDER
          git status

      - name: Push to gh-pages
        run: |
          cd $GH_PAGES_FOLDER

          echo "Configuring git push"
          git config user.name "GH actions toolkit builder"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          echo "Running git commit"
          git add .
          git commit -m "Auto-commit of toolkit build for ${{ github.repository }}@${{ github.sha }}"

          echo "Running git status"
          git status

          # Push all changes in one commit to the gh-pages branch
          echo "Build branch ready to go. Pushing to Github..."
          git push origin ${GH_PAGES_BRANCH}

          echo "ðŸŽ‰ New version deployed ðŸŽŠ"
