name: Check clang-format
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: "src"
            exclude: "(hum|midi|json|pugi)"
          - check: "include"
            exclude: "(hum|midi|json|pugi|utf8|win32|zip)"
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v3.4.0
        with:
          clang-format-version: "11"
          check-path: ${{ matrix.path['check'] }}
          exclude-regex: ${{ matrix.path['exclude'] }}
